version: '3'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
      - uploads_data:/app/static/uploads
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      # Configuração para desenvolvimento local
      - DATABASE_URL=postgresql://iamsurfer:iamsurfer@db/iamsurfer
      # Configuração para produção no Render (comentada)
      # - DATABASE_URL=postgresql://iamsurfer_db_user:9sdJXz63jfoSV1lxfQN8bGgPzQaATmSU@dpg-cvqp848gjchc7395pfhg-a/iamsurfer_db
    depends_on:
      - db
  
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=iamsurfer
      - POSTGRES_USER=iamsurfer
      - POSTGRES_DB=iamsurfer
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  uploads_data: 