"""Add is_public and indexes

Revision ID: 185f58bc7579
Revises: b401ab1366af
Create Date: 2026-03-12 16:50:02.343857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '185f58bc7579'
down_revision = 'b401ab1366af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_post_user_time', 'post', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_spotreport_user_time', 'spot_report', ['user_id', 'report_date'], unique=False)
    op.add_column('user', sa.Column('is_public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_public')
    op.drop_index('idx_spotreport_user_time', table_name='spot_report')
    op.drop_index('idx_post_user_time', table_name='post')
    # ### end Alembic commands ###
