"""Automatic migration

Revision ID: 7935af6613ef
Revises: b8db3f0b519f
Create Date: 2025-06-25 23:38:06.652765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7935af6613ef'
down_revision = 'b8db3f0b519f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_post_image_hash'), table_name='post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_post_image_hash'), 'post', ['image_hash'], unique=False)
    # ### end Alembic commands ###
