"""fix_city_surfspot_relationship

Revision ID: 806ca47e42e2
Revises: add_all_changes
Create Date: 2025-05-19 23:30:19.433171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '806ca47e42e2'
down_revision = 'add_all_changes'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'photographer_subscription')
    op.drop_column('user', 'service_provider_subscription')
    op.drop_column('user', 'is_local_business')
    op.drop_column('user', 'influencer_subscription')
    op.drop_column('user', 'is_photographer')
    op.drop_column('user', 'is_influencer')
    op.drop_column('user', 'is_service_provider')
    op.drop_column('user', 'business_subscription')
    op.drop_column('user', 'is_pro_athlete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_pro_athlete', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('business_subscription', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('is_service_provider', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('is_influencer', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('is_photographer', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('influencer_subscription', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('is_local_business', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('service_provider_subscription', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('photographer_subscription', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
