"""Automatic migration

Revision ID: 83319ea75360
Revises: 8c9d6a92e18c
Create Date: 2025-05-08 00:38:17.995793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83319ea75360'
down_revision = '8c9d6a92e18c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surf_trip', sa.Column('destination_text', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surf_trip', 'destination_text')
    # ### end Alembic commands ###
