"""increase_difficulty_level_size

Revision ID: 889708597c09
Revises: 806ca47e42e2
Create Date: 2025-05-19 23:41:27.733601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '889708597c09'
down_revision = '806ca47e42e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('surf_spot', 'difficulty_level',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('surf_spot', 'difficulty_level',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
