"""Add rejected_by and rejected_at fields to Spot model

Revision ID: 8a80fd375570
Revises: 889708597c09
Create Date: 2025-06-18 23:27:44.831527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a80fd375570'
down_revision = '889708597c09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spot', sa.Column('rejected_by', sa.Integer(), nullable=True))
    op.add_column('spot', sa.Column('rejected_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'spot', 'user', ['rejected_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'spot', type_='foreignkey')
    op.drop_column('spot', 'rejected_at')
    op.drop_column('spot', 'rejected_by')
    # ### end Alembic commands ###
