"""Automatic migration

Revision ID: 8c9d6a92e18c
Revises: 1dca021ae18e
Create Date: 2025-05-08 00:28:48.910261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c9d6a92e18c'
down_revision = '1dca021ae18e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surf_trip', 'destination_text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surf_trip', sa.Column('destination_text', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
