"""Automatic migration

Revision ID: de1879d8c7dd
Revises: b8143638a4dd
Create Date: 2025-04-09 17:45:09.821551

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'de1879d8c7dd'
down_revision = 'b8143638a4dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('post', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('post', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
